# docker-compose.yml
networks:
  club_moto_network:
    driver: bridge

services:
  php:
    container_name: club_moto_php
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html/
    depends_on:
      - database
    networks:
      - club_moto_network
  
  nginx:
    container_name: club_moto_nginx
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - .:/var/www/html/
    ports:
      - 8081:80
    depends_on:
      - php
    networks:
      - club_moto_network
  
